### PR TITLE
Add GitHub Actions build workflow

### PR DESCRIPTION
**Pull request by mwarzynski**
I would like to propose adding GitHub Actions workflow.
Example Run: https://github.com/mwarzynski/reef-client/actions/runs/702840521

Workflow checks if state of the source code allows to successfully build the project. It's triggered for every push to the repository.

What do you think about adjusting the code accordingly to the defined linter rules? Currently, if we run the linter, it will return errors (at least it didn't pass for `npm run lint`).
I also would like to propose adding a requirement to the PR for a successful build (if my PR will be merged).

### CODE REVIEW

**Comment by mwarzynski** [comment]
@filipbarak What do you think about introducing GitHub Actions to the repository? Would you please share your thoughts (approve or reject)?

**Comment by filipbarak** [comment]
Hi @mwarzynski , GH Actions could be a nice-to-have feature on this repo. Let me play with your PR a bit and I'll let you know.

**Comment by mwarzynski** [comment]
@filipbarak Have you managed to take a look at this PR?

**Comment by mwarzynski** [comment]
Closed due to lack of input from the maintainers side.

**Pull request closed without merging**
